FROM python:slim

WORKDIR /opt/SAPPORO-service

RUN apt update && \
    apt install -y \
    build-essential \
    iproute2 \
    jq \
    procps && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.dev.txt /tmp

RUN pip install -U pip && \
    pip install -r /tmp/requirements.dev.txt && \
    rm -rf /tmp/requirements.dev.txt

COPY entry_point.dev.sh /opt/SAPPORO-service/entry_point.sh

CMD ["tail", "-f", "/dev/null"]
