FROM python:alpine

WORKDIR /opt/SAPPORO-service

RUN apk --update add --no-cache \
    gcc \
    jq \
    libc-dev \
    libc6-compat \
    libltdl \
    libxml2-dev \
    libxslt-dev \
    linux-headers \
    pcre-dev

COPY requirements.dev.txt /tmp

RUN pip install -U pip && \
    pip install -r /tmp/requirements.dev.txt && \
    rm -rf /tmp/requirements.dev.txt

COPY entry_point.dev.sh /opt/SAPPORO-service/entry_point.sh

CMD ["tail", "-f", "/dev/null"]
