#!/bin/bash
cd `dirname $0`
CMDNAME=`basename $0`

function usage () {
  cat << EOS
Usage: $CMDNAME
Script to clean SAPPORO-service.

Option:
  -h, --help                  Print usage.
EOS
}

while [ $# -gt 0 ]; do
  case $1 in
    "-h" | "--help" )
      usage
      exit 1
      ;;
    * )
      usage
      exit 1
      ;;
  esac
done

SERVICE_ROOT=$(cd $(dirname $0)/.. && pwd)
DOCKER_COMPOSE_CONFIG_FILE=${SERVICE_ROOT}/docker-compose.yml

echo "Start service-clean..."
docker network rm sapporo-network > /dev/null 2>&1
docker network rm sapporo-service_default > /dev/null 2>&1
rm -rf "${SERVICE_ROOT}/config/uwsgi.sock"
rm -rf "${SERVICE_ROOT}/run/*"
rm -rf "${SERVICE_ROOT}/log/*"
cat << EOS > ${DOCKER_COMPOSE_CONFIG_FILE}
version: "3"
services:
  app:
    image: suecharo/sapporo-service:v0.3.4
    container_name: sapporo-service-app
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /tmp:/tmp
      - ./SAPPORO-service:/opt/SAPPORO-service/SAPPORO-service
      - ./config:/opt/SAPPORO-service/config
      - ./log:/opt/SAPPORO-service/log
      - ./run:/opt/SAPPORO-service/run
    networks:
      - sapporo
    environment:
      - LOG_LEVEL=INFO # DEBUG or INFO
      - ENABLE_GET_RUNS=False
      - ENABLE_TOKEN_AUTH=False
    command: ["/bin/bash", "/opt/SAPPORO-service/entry_point.sh"]
  web:
    image: nginx:stable-alpine
    container_name: sapporo-service-web
    depends_on:
      - app
    restart: always
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config:/opt/SAPPORO-service/config
      - ./log:/opt/SAPPORO-service/log
    networks:
      - sapporo
    ports:
      - 1122:80

networks:
  sapporo:
    external:
      name: sapporo-network
EOS

echo "Finish service-down..."
