FROM python:3.7-slim

WORKDIR /opt/SAPPORO-service

RUN apt update \
 && apt install -y \
    build-essential \
    curl \
    libltdl7 \
    silversearcher-ag \
    tmux \
    tree \
    unzip \
    vim \
 && apt clean \
 && rm -rf /var/lib/apt/lists/*

COPY requirements.dev.txt /opt/SAPPORO-service
COPY .tmux.conf /root

RUN pip install -r requirements.dev.txt

CMD ["tail", "-f", "/dev/null"]
