FROM python:3.7-slim

WORKDIR /tmp

RUN apt update \
 && apt install -y \
    vim \
    build-essential \
    curl \
    jq \
    libltdl7 \
    procps \
    silversearcher-ag \
    tree \
    unzip \
 && apt clean \
 && rm -rf /var/lib/apt/lists/*

COPY requirements.dev.txt /tmp

RUN pip install -r requirements.dev.txt

CMD ["tail", "-f", "/dev/null"]
