#!/bin/bash
cd `dirname $0`
CMDNAME=`basename $0`

function usage () {
  cat << EOS
Usage: $CMDNAME
Script to clean SAPPORO-web.

Option:
  -h, --help                  Print usage.
EOS
}

while [ $# -gt 0 ]; do
  case $1 in
    "-h" | "--help" )
      usage
      exit 1
      ;;
    * )
      usage
      exit 1
      ;;
  esac
done

WEB_ROOT=$(cd $(dirname $0)/.. && pwd)
DOCKER_COMPOSE_CONFIG_FILE="${WEB_ROOT}/docker-compose.yml"

echo "Start web-clean..."
docker network rm sapporo-network > /dev/null 2>&1
docker network rm sapporo-web_default > /dev/null 2>&1
docker volume rm sapporo-web_postgres-data > /dev/null 2>&1
rm -rf "${WEB_ROOT}/config/uwsgi.sock"
rm -rf "${WEB_ROOT}/log/*"
rm -rf "${WEB_ROOT}/SAPPORO-web/app/migrations"
rm -rf "${WEB_ROOT}/SAPPORO-web/static"
cat << EOS > ${DOCKER_COMPOSE_CONFIG_FILE}
version: "3"
services:
  app:
    image: suecharo/sapporo-web:v0.3.4
    container_name: sapporo-web-app
    depends_on:
      - database
    restart: always
    volumes:
      - ./SAPPORO-web:/opt/SAPPORO-web/SAPPORO-web
      - ./config:/opt/SAPPORO-web/config
      - ./log:/opt/SAPPORO-web/log
    networks:
      - sapporo
    environment:
      - LOG_LEVEL=INFO # DEBUG or INFO
      - LANGUAGE_CODE=en
      - TIME_ZONE=Asia/Tokyo
      - ENABLE_USER_SIGNUP=True
      - POSTGRES_USER=sapporo-web-user
      - POSTGRES_PASSWORD=sapporo-web-passwd
      - POSTGRES_DB=sapporo-web
      - POSTGRES_PORT=5432
    command: ["/bin/bash", "/opt/SAPPORO-web/entry_point.sh"]
  web:
    image: nginx:stable-alpine
    container_name: sapporo-web-web
    depends_on:
      - app
    restart: always
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config:/opt/SAPPORO-web/config
      - ./log:/opt/SAPPORO-web/log
      - ./SAPPORO-web/static:/opt/SAPPORO-web/SAPPORO-web/static
    networks:
      - sapporo
    ports:
      - 1121:80
  database:
    image: postgres:alpine
    container_name: sapporo-web-database
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - sapporo
    environment:
      - POSTGRES_USER=sapporo-web-user
      - POSTGRES_PASSWORD=sapporo-web-passwd
      - POSTGRES_DB=sapporo-web
      - POSTGRES_PORT=5432

volumes:
  postgres-data:

networks:
  sapporo:
    external:
      name: sapporo-network
EOS

echo "Finish web-down..."
