FROM python:alpine

WORKDIR /opt/SAPPORO-service

RUN apk --update add --no-cache \
    gcc \
    libc-dev \
    libxml2-dev \
    libxslt-dev \
    linux-headers \
    pcre-dev

COPY requirements.dev.txt /tmp

RUN pip install -U pip && \
    pip install -r /tmp/requirements.dev.txt && \
    rm -rf /tmp/requirements.dev.txt

CMD ["tail", "-f", "/dev/null"]
