FROM python:3.7-slim

WORKDIR /opt/NIG-web

RUN apt update \
 && apt install -y \
    build-essential \
    curl \
    silversearcher-ag \
    tree \
    vim \
 && apt clean \
 && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /opt/NIG-web
RUN pip install -r requirements.txt

CMD ["tail", "-f", "/dev/null"]